### ISSUE TITLE
process_google.py MemoryError

### ISSUE THREAD

**Issue by pushkalkatara** [microsoft/EdgeML#122]
The script [process_google.py](https://github.com/microsoft/EdgeML/blob/master/pytorch/examples/SRNN/process_google.py) reads all the .wav in a numpy array which might cause a memory error on many systems.
Either use of disk storage through `numpy.memmap` or storing array as `.HDF5` with `PyTables` or use of some library like Pandas might solve this issue.

**Comment by pushkalkatara** [comment]
Error reproduction 
```
Traceback (most recent call last):
  File "process_google.py", line 257, in <module>
    numFilt, samplerate, winlen, winstep)
  File "process_google.py", line 173, in extractFeatures
    allSamples = np.zeros((len(fileList), maxlen))
MemoryError
```
